substitutions:
  device_name: tater-display-livingroom
  friendly_name: Tater Display Livingroom

  # ─────────────────────────────────────────
  # EASY TO CHANGE HOME ASSISTANT ENTITIES
  # ─────────────────────────────────────────
  sensor_temp_out: sensor.weather_outdoor_temperature
  sensor_temp_in: sensor.living_room_temperature

  sensor_humidity_out: sensor.humidity
  sensor_humidity_in: sensor.up_sense_humidity_level

  sensor_wind_speed: sensor.wind_speed
  sensor_rain_rate: sensor.rain_rate
  sensor_lightning_strikes: sensor.weather_lightning_strikes

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.12.2

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.4.20.237

logger:
api:
ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: ha_time

# ─────────────────────────────────────────
# HOME ASSISTANT SENSORS
# ─────────────────────────────────────────
sensor:
  - platform: homeassistant
    id: temp_out
    entity_id: ${sensor_temp_out}

  - platform: homeassistant
    id: temp_in
    entity_id: ${sensor_temp_in}

  - platform: homeassistant
    id: humidity_out
    entity_id: ${sensor_humidity_out}

  - platform: homeassistant
    id: humidity_in
    entity_id: ${sensor_humidity_in}

  - platform: homeassistant
    id: wind_speed
    entity_id: ${sensor_wind_speed}

  - platform: homeassistant
    id: rain_rate
    entity_id: ${sensor_rain_rate}

  - platform: homeassistant
    id: lightning_strikes
    entity_id: ${sensor_lightning_strikes}

# ─────────────────────────────────────────
# S3 BOX DISPLAY WIRING
# ─────────────────────────────────────────
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: lcd_backlight
    name: LCD Backlight
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 50ms

# ─────────────────────────────────────────
# COLORS
# ─────────────────────────────────────────
color:
  - id: black
    red: 0%
    green: 0%
    blue: 0%
  - id: white
    red: 100%
    green: 100%
    blue: 100%
  - id: orange
    red: 100%
    green: 45%
    blue: 0%

# ─────────────────────────────────────────
# SPINNER STATE
# ─────────────────────────────────────────
globals:
  - id: spinner_idx
    type: int
    restore_value: no
    initial_value: "0"

interval:
  - interval: 2s
    then:
      - lambda: |-
          id(spinner_idx) = (id(spinner_idx) + 1) % 3;

# ─────────────────────────────────────────
# FONTS + ICONS
# ─────────────────────────────────────────
font:
  # Text fonts
  - file: "https://github.com/TaterTotterson/S3Box-HomeAssistant/raw/refs/heads/main/fonts/consola.ttf"
    id: consola_20
    size: 20

  - file: "https://github.com/TaterTotterson/S3Box-HomeAssistant/raw/refs/heads/main/fonts/consola.ttf"
    id: consola_30
    size: 30

  - file: "https://github.com/TaterTotterson/S3Box-HomeAssistant/raw/refs/heads/main/fonts/consola.ttf"
    id: consola_40
    size: 40

  - file: "https://github.com/TaterTotterson/S3Box-HomeAssistant/raw/refs/heads/main/fonts/consola.ttf"
    id: consola_60
    size: 60

  # Icons (MDI)
  - file: "https://github.com/TaterTotterson/S3Box-HomeAssistant/raw/refs/heads/main/fonts/materialdesignicons-webfont.ttf"
    id: mdi_80
    size: 80
    glyphs:
      - "\U000F059E" # wind
      - "\U000F0597" # rain
      - "\U000F0593" # lightning

# ─────────────────────────────────────────
# DISPLAY
# ─────────────────────────────────────────
display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    data_rate: 40MHz
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    invert_colors: false
    update_interval: 1s
    lambda: |-
      auto now = id(ha_time).now();
      if (!now.is_valid()) {
        it.fill(id(black));
        it.print(160, 120, id(consola_40), id(white), TextAlign::CENTER, "Waiting for HA...");
        return;
      }

      it.fill(id(black));

      // DATE
      it.strftime(160, 6, id(consola_30), id(white), TextAlign::TOP_CENTER, "%A %b %d", now);

      // TIME
      it.strftime(160, 42, id(consola_60), id(white), TextAlign::TOP_CENTER, "%I:%M", now);
      it.strftime(285, 68, id(consola_30), id(orange), TextAlign::TOP_RIGHT, "%p", now);

      // IN (label same, temp same size, humidity smaller)
      it.printf(10, 160, id(consola_30), id(white), "IN");
      it.printf(10, 185, id(consola_30), id(orange), "%.1f", id(temp_in).state);
      it.printf(10, 212, id(consola_20), id(white), "%.0f%%", id(humidity_in).state);

      // OUT (label same, temp same size, humidity smaller)
      it.printf(310, 160, id(consola_30), id(white), TextAlign::TOP_RIGHT, "OUT");
      it.printf(310, 185, id(consola_30), id(orange), TextAlign::TOP_RIGHT, "%.1f", id(temp_out).state);
      it.printf(310, 212, id(consola_20), id(white), TextAlign::TOP_RIGHT, "%.0f%%", id(humidity_out).state);

      // Spinner icons
      const char* icons[] = {
        "\U000F059E", // wind
        "\U000F0597", // rain
        "\U000F0593"  // lightning
      };

      it.print(160, 105, id(mdi_80), id(orange), TextAlign::TOP_CENTER, icons[id(spinner_idx)]);

      // Spinner value
      float value = 0.0f;
      if (id(spinner_idx) == 0) value = id(wind_speed).state;
      else if (id(spinner_idx) == 1) value = id(rain_rate).state;
      else value = id(lightning_strikes).state;

      it.printf(160, 182, id(consola_30), id(white), TextAlign::TOP_CENTER, "%.1f", value);
